def printHeader():

    print("#############################################")
    print("# Tooling Inspection Motion Controller GUI  #")
    print("# Tool: Access Hole Cover                   #")
    print("# PLM:  DOC-0009-1257                       #")
    print("#############################################")
    print("")
    print("Author:   Timothy Clark")
    print("Email:    timoty.clark@ge.com")
    print("Date:     07/21/2017")
    print("Company:  GE Hitachi")
    print("Description")
    print("   - Graphical User Interface using Tkinter package")
    print("   - Requires python 3.6")
    print("   - Lienar amplifiers to reduce EMI: Aerotech Ensemble ML")
    print("   - Serial communication with Aerobasic ASCII commands")
    print("")
    print("=============================================================")
    print("")
